### ISSUE TITLE
大佬,牛杯......

### ISSUE THREAD

**Issue by zeled520** [justorez/bookmark-cleaner#1]
好用..对了.如果针对类似笔趣阁这类老是换地址...能自动换新网址,名称不变吗?

**Comment by zeled520** [comment]
为啥我网页里一个书签都没有

**Comment by justorez** [comment]
@zeled520 没有考虑类似功能，我只是因为自己书签存的太多了，又有点书签洁癖，就想把已经挂掉的清一清
